#!/usr/bin/env zsh
# mise description="install gdb"

# use global variable HOME_DIR PROJECT_DIR 
VERSION=15.1
TARGET=riscv64-unknown-elf
PREFIX=${HOME_DIR}private/tool/gdb/${VERSION}/${TARGET}/
PYTHON=/home/leap/miniconda3/bin/python3 # can't use conda's python

sudo apt-get install libncurses5-dev texinfo libreadline-dev

if [[ ! -d ${PROJECT_DIR}gdb-$VERSION ]]; then 
    wget https://ftp.gnu.org/gnu/gdb/gdb-$VERSION.tar.xz -P $PROJECT_DIR
    tar -xvJf ${PROJECT_DIR}gdb-$VERSION.tar.xz -C $PROJECT_DIR
    rm ${PROJECT_DIR}gdb-$VERSION.tar.xz
fi

cd ${PROJECT_DIR}gdb-$VERSION
./configure --prefix=$PREFIX --target=$TARGET --with-python=$PYTHON --enable-tui=yes
make -j$(nproc)
make install

if [[ ! -e ${HOME_DIR}.gdbinit ]]; then 
    wget https://github.com/cyrus-and/gdb-dashboard/raw/master/.gdbinit -P ~ # gdb-dashboard
fi