#!/usr/bin/env zsh
# mise description="download and install miniconda on Linux"

if [[ ! -d ~/miniconda3 ]]; then
    mkdir -p ~/miniconda3

    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh

    zsh ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3

    rm -rf ~/miniconda3/miniconda.sh
fi

~/miniconda3/bin/conda init zsh

# Windows:
# curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -o miniconda.exe
# start /wait "" miniconda.exe /S
# del miniconda.exe 
