[windows]
commands = [
    'curl https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -o miniconda.exe ',
    'start /wait "" miniconda.exe /S',
    'del miniconda.exe'
]

[windows.links]
original = 'link'

[linux]
commands = [
    'mkdir -p ~/miniconda3 ',
    'wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh ',
    'bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 ',
    'rm -rf ~/miniconda3/miniconda.sh ',
    '~/miniconda3/bin/conda init zsh '
]

[linux.links]
original = 'link'