[windows]
commands = '''
Write-Host "Hello Once!"
'''

[windows.links]
"win_settings.json" = '~/AppData/Roaming/Code/User/settings.json'

snippets = '~/AppData/Roaming/Code/User/snippets'

"keybindings.json" = '~/AppData/Roaming/Code/User/keybindings.json'

"workspaces/main.code-workspace" = '~/AppData/Roaming/Code/User/workspaces/main.code-workspace'
"workspaces/Rust.code-workspace" = '~/AppData/Roaming/Code/User/workspaces/Rust.code-workspace'
"workspaces/Python.code-workspace" = '~/AppData/Roaming/Code/User/workspaces/Python.code-workspace'
"workspaces/TypeScript.code-workspace" = '~/AppData/Roaming/Code/User/workspaces/TypeScript.code-workspace'
"workspaces/LaTex.code-workspace" = '~/AppData/Roaming/Code/User/workspaces/LaTex.code-workspace'

[linux]
commands = '''
echo "Hello Once!"
'''

[linux.links]
"wsl_settings.json" = '~/.vscode-server/data/Machine/settings.json'

"workspaces/Main.code-workspace" = '~/.vscode-server/data/User/workspaces/main.code-workspace'
"workspaces/Rust.code-workspace" = '~/.vscode-server/data/User/workspaces/Rust.code-workspace'
"workspaces/Python.code-workspace" = '~/.vscode-server/data/User/workspaces/Python.code-workspace'
"workspaces/C_CPP.code-workspace" = '~/.vscode-server/data/User/workspaces/C_CPP.code-workspace'
"workspaces/Embeded.code-workspace" = '~/.vscode-server/data/User/workspaces/Embeded.code-workspace'
"workspaces/Typst.code-workspace" = '~/.vscode-server/data/User/workspaces/Typst.code-workspace'