[windows]
commands = [
    ' '
]

[windows.links]
original = 'link'

[linux]
commands = [
    'sudo apt install zsh ',
    'chsh -s /bin/zsh ',
    'bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)" '
]

[linux.links]
"settings.json" = '~/.vscode-server/data/Machine/settings.json'
workspaces = '~/.vscode-server/data/User/workspaces'
